export const subtitles = [
  "Small progress every day leads to big offers.",
  "Let's sharpen your problem-solving skills.",
  "Today's effort is tomorrow's confidence.",
  "Stay consistent. The results will follow.",
  "Interview success is built one problem at a time.",
  "Keep your streak alive.",
  "The next solved problem could teach you something new.",
  "Every solved problem makes you interview stronger.",
  "Consistency beats intensity.",
  "One more problem. One step closer.",
  "Let's build something impressive today.",
  "You're closer than yesterday.",
  "Push yourself a little further today.",
  "Every expert was once a beginner.",
  "Code. Learn. Improve. Repeat.",
  "Trust the process.",
  "Discipline creates opportunities.",
  "Another day. Another challenge.",
  "Let's make today's graph greener.",
];